DROP TABLE IF EXISTS "person" CASCADE;
CREATE TABLE "public"."person"
(
    "id"   bigint NOT NULL,
    "name" character varying(255),
    CONSTRAINT "person_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "booking" CASCADE;
CREATE TABLE "public"."booking"
(
    "id"        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "person_id" bigint,
    CONSTRAINT "booking_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "organization" CASCADE;
CREATE TABLE "public"."organization"
(
    "id"            bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "average_check" double precision,
    "name"          character varying(255),
    "rating"        double precision,
    "schedule"      character varying(255),
    "type_organization" character varying(255),
    CONSTRAINT "organization_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "some_object" CASCADE;
CREATE TABLE "public"."some_object"
(
    "id"              bigint NOT NULL,
    "description"     character varying(255),
    "organization_id" bigint,
    CONSTRAINT "some_object_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

DROP TABLE IF EXISTS "reservation" CASCADE;
CREATE TABLE "public"."reservation"
(
    "id"             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "beginning"      integer,
    "date"           character varying(255),
    "ending"         integer,
    "booking_id"     bigint,
    "some_object_id" bigint,
    CONSTRAINT "reservation_pkey" PRIMARY KEY ("id")
) WITH (oids = false);

ALTER TABLE ONLY "public"."booking"
    ADD CONSTRAINT "fkh74dg5tgqi0nybfwudce2ha5g" FOREIGN KEY (person_id) REFERENCES person (id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."reservation"
    ADD CONSTRAINT "fk2bxb5botsba4wo5hofrkra4ba" FOREIGN KEY (some_object_id) REFERENCES some_object (id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."reservation"
    ADD CONSTRAINT "fk6xxrh276602h6dtixgnny5xx3" FOREIGN KEY (booking_id) REFERENCES booking (id) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."some_object"
    ADD CONSTRAINT "fkc9mnkwikcw97qdp7sacd2eein" FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE;